[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
callee = {path = "../callee" }

[lints.rust]
unexpected_cfgs = { level = "forbid"}

[profile.release]
lto = "fat"

[profile.dev]
lto = "fat"
opt-level = 2

