name: Validate Version

on:
  push:
  pull_request:

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run validate-version.sh
        run: ./validate-version.sh
        shell: bash
